### ISSUE TITLE
[Enhancement] Add support for macOS?

### ISSUE THREAD

**Issue by ghost** [Akascape/CTkThemeMaker#1]
As a macOS and CTk user, I was hoping to find a way to make themes easier. Unfortunately, when trying to save my theme and quick-test it, the paths were only for Windows.

If you want, I could submit a PR adding macOS support. I'm also ready to do macOS testing.

**Comment by Akascape** [comment]
@dishb 
Yes, you can give a PR. I will add the macos support by tomorrow.

**Comment by ghost** [comment]
@Akascape - PR submitted #2. Will close this issue when PR is merged.

**Comment by Akascape** [comment]
@dishb Hey, I just updated the code. It should now work on linux/macos properly.

**Comment by ghost** [comment]
@Akascape - Will test the latest version soon today. With the results, we can close this issue.

**Comment by ghost** [comment]
@Akascape - Just tested the repository code (branch: main), everything works beautifully!

CustomTkinter: 5.1.3
Python: 3.11.3
macOS: 12.6.6
