### ISSUE TITLE
Add dependencies

### ISSUE THREAD

**Issue by henryruhs** [Akascape/CTkThemeMaker#3]
Hey, don't you think having a `requirements.txt` would help?

```
tk
customtkinter
pillow
```

**Comment by Akascape** [comment]
Pillow is not necessary for the thememaker but only for the example, customtkinter is the only package you need. Tkinter is default library. But these libraries are generally installed by everyone.

**Comment by henryruhs** [comment]
`from PIL import Image`

Pillow is not needed!?

**Comment by Akascape** [comment]
@henryruhs only for the example. Not inside thememaker. Thememaker cam run without the example.

**Comment by Akascape** [comment]
@henryruhs These libraries are generally installed by everyone.

**Comment by henryruhs** [comment]
If you say so, was not installed in venv. Whatever, I close it...

**Comment by Akascape** [comment]
@henryruhs Ok, I will add the requirements if you say so. Not a big deal.
